sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t av/test-repo -f Dockerfile.dev .

script:
    - docker run -e CI=true av/test-repo npm test run -- --coverage